### ISSUE TITLE
Can't download the pre-trained models

### ISSUE THREAD

**Issue by mmaaz60** [liuqk3/OTCD#2]
Hi Team,

I can't download the pre-trained models from the link you provided in the readme file. It looks like the URL no longer exists. Can you please provide me an updated URL to download the pre-trained models.

Thanks

**Comment by liuqk3** [comment]
Hi, @mmaaz60,
The models are uploaded to BaiduYun, If you can not download the models, I can email to you.

**Comment by ntnHome** [comment]
Hi.
I tried downloading. I have the .deb file, 68.7MB. Whe I click on it, it asks for root passwork for installation, which I give, and then does something but I don't see any data in my directory.
Does it copy the data to some other directory?
Thanks and regards.

**Comment by ntnHome** [comment]
Hi  @mmaaz60,
Could you solve the problem?

**Comment by Akhil-Raj** [comment]
Same problem. Can't seem to download the file. Kindly look through it @liuqk3?

**Comment by liuqk3** [comment]
All models have been uploaded to OneDrive now. For all users not in China, the models can be downloaded for this link  "https://mailustceducn-my.sharepoint.com/:f:/g/personal/liuqk3_mail_ustc_edu_cn/Eov9rFdHy7RPrV5YvrIxQkgBQ9cqfrKfNYX5NV0qBRixWQ?e=2qWgua".
